name: CI/CD counter app

on:
  push:
    branches: [main]

jobs:
  #First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_SECRET_KEY  }}
          HOSTNAME: ${{ secrets.SERVER_IP  }}
          USER_NAME: ${{ secrets.SERVER_USER  }}

        run: |
          echo "$PRIVATE_KEY" > deploy_key && chmod 600 deploy_key
          ssh -o StrictHostKeyChecking=no -i deploy_key ${USER_NAME}@${HOSTNAME} '

             #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/CounterApp &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main
          '
