name: CI/CD test app
on:
  workflow_dispatch:

jobs:
  #Build first, deploy later
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  Deploy:
    needs: Build
    if: github.event.workflow_run.conclusion == 'success' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2

      # - name: Set up Node.js 16.x
      #   uses: actions/setup-node@v2.1.5
      #   with:
      #     node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Build the project
        run: yarn build

      # - name: Connect to server and restart PM2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_IP }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.AWS_SECRET_KEY}}
      #     script: |
      #       cd CI-CD/CI-CD-Test/
      #       curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      #       source ~/.nvm/nvm.sh && nvm install 16.17.0 && nvm use 16.17.0
      #       git -c "user.name=${{ secrets.GIT_NAME }}" -c "user.password=${{ secrets.GIT_SECRET_KEY }}" pull origin main
      #       yarn
      #       yarn build
      #       pm2 restart CI_CD-Test
# name: learn-github-actions
# on:
#   push:
#     branches:
#       - main
# jobs:
#   install-package:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v2
#       - run: yarn --version
#       - run: yarn
#       - run: yarn test
#       - run: yarn build
#       - run: pm2 restart nest-ci-cd.api
